---
title: "Week 7 - Working with HTML, JSON, and XML file"
output: html_document
---


# Import Libraries:
```{r}
library(rvest)
library(dplyr)
library(tidyverse)
library(DT)
```

# Reading HTML file
```{r }
# Get working directory path
github_link <- "https://raw.githubusercontent.com/uzmabb182/CUNY-SPS-Assignments/main/data_607/week7/books_data.html"

github_link
```

```{r}
# Start by reading a HTML page with read_html():

html_data<- read_html(github_link)

html_data
```
# Converting the HTML data into dataframe
```{r}
data <-html_table(html_data)
html_df <- as.data.frame(data)

html_df
```

```{r}

```

# Load the JSON Package


```{r}
library("rjson")
```

# Read a JSON file

```{r}
# Give the input file name to the function.
github_link = "https://raw.githubusercontent.com/uzmabb182/CUNY-SPS-Assignments/main/data_607/week7/books_data.json"

json_data <- fromJSON(file = github_link)

str(json_data)
```
# loading the library and other important packages

```{r}
library("XML")
library("methods")

```

# the contents of books_data.xml are parsed

```{r}

github_link = "https://raw.githubusercontent.com/uzmabb182/CUNY-SPS-Assignments/main/data_607/week7/books_data.XML"

github_link
```

```{r}
library(httr)
library(XML)

r = GET(github_link)
xml_data <- xmlTreeParse(r, useInternal=TRUE)
 
print(xml_data)
```
# Now compare the dataframes
```{r}
library(arsenal)
```

```{r}

```

```{r}

```


