---
title: "Week Eleven - Recommender Systems"
output: html_document
---

Links:

Reference 1: https://www.enterpriseai.news/2021/09/15/heres-how-ebay-is-using-optimization-techniques-to-scale-ai-for-its-recommendation-systems/

Reference 2: https://www.forbes.com/sites/bernardmarr/2019/04/26/the-amazing-ways-ebay-is-using-artificial-intelligence-to-boost-business-success/?sh=6facedb62c2e


### eBay Recommender sysytem

A free recommondation is always appealing to people, especially when it is done at the right shopping state of mind and when it is suggested intelligently.eBay is an AI driven global maket place with different kind of product from from all over the world.For an e-commerce business of this large scalibility, it needs to have a very accurate recommender system. What it means is that after training the model, it needs to have a lot of optimization done to predict accurately.

### Utilization of Machine Learning Model And AI Techniques:

1. It uses machine learning and AI techniques, for the following tasks: 

2. natural language processing (NLP) for recommending the products to its audience.

3. Performing the features extraction from the product reviews.

4. Filtering of product reviews.

5. Shipping and delivery estimation.

6. Payment and fraud detection between two parties business dealing.

7. It uses neural network-based transformer models, like BERT, GPT-2, and GPT-3, for inferring information from  text.

8. It uses a supervised machine learning algorithm, K nearesr neighbor (KNN) image classification.

9. For text and summerization, it uses eBert transformer model.Transformer includes two separate mechanisms — an encoder that reads the text input and a decoder that produces a prediction for the task.

10. Since, eBert is not suitable to use online for inferencing purposes, eBay uses distillation, a way to compress a model and quantization techniques to improve the accuracy of outcome and speed of the model.


### Scenario Design

1. Who are your target users?

These target user’s are the sellers, since eBay originally started as an auction site and for buyer’s who either are looking for a very specific item form all over the world or good deal for an item when they are comparing the price. 

2. What are their key goals?

eBay's key goals are as follows:

a. Provide best experience to their buysers and sellers. 


3. How can you help them accomplish those goals?

eBay’s returns the top related items with filter’s and sorting options to aid the user as well as a side panel of related items available for browsing.

Reverse Engineer

how to improve the site's recommendation capabilities